apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstore-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:your-user/your-repo.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
