apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: git@github.com:your-user/your-repo.git
      name: private-repo
      type: git
      username: git
      password: <YOUR_PERSONAL_ACCESS_TOKEN>
