apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
        - name: bookstore
          image: your-dockerhub-username/bookstore:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_NAME
              value: bookstore_db
            - name: DATABASE_USER
              value: bookstore_user
            - name: DATABASE_PASSWORD
              value: bookstore_pass
