version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: bookstore_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: bookstore_db
      DATABASE_USER: bookstore_user
      DATABASE_PASSWORD: bookstore_pass
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
